name: Open Science Workshop in Taiwan - Brainhack Project Submission
description: This provides the backbone structure for your project description. Please follow along to submit your project!
title: "<My Project Name>"
labels: ["Hackathon Project"]
assignees:
  - juchiyu
  - smoia
body:
  - type: markdown
    attributes:
      value: |
        **Welcome to the BrainHack of "Open Minds, Open Data: The 2025 Taiwan Open Brain Science Workshop 開放思維，開放數據: 台灣開放腦科學工作坊" 🎉**
        
        *We have prepared this template to help with your project submission. Please fill in the template (at least all 'required' items must be provided) and we will assign a 'project monitor' to follow your submission.
        If at any time you need help or anything is unclear, please add a comment and ping your project monitor.*

        > This event is hosted by the Graduate Institute of Mind, Brain and Consciousness (GIMBC), Taipei Medical University, in collaboration with the OHBM Open Science Special Interest Group (OS-SIG) and the Open Science Room (OSR).
        > This template is inspired by [OHBM BrainHack 2025](https://github.com/ohbm/hackathon2025).

        Thank you!

  - type: input
    id: title
    attributes:
      label: Title
      description: Name of your awesome project. Please also update the title of the issue to be the title of your project
    validations:
      required: true

  - type: textarea
    id: goals
    attributes:
      label: Short description and the goals for the OHBM BrainHack
      description: Please provide a short description and goals for the hackathon, check [the guide](https://github.com/ohbm/hackathon2025/blob/main/PROJECTS_HANDBOOK.md#goals) for suggestions
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Link to the Project
      description: Please provide **one URL** for the project, e.g. GitHub repository.
    validations:
      required: true

  - type: input
    id: website-image
    attributes:
      label: Image/Logo for the OHBM brainhack website
      description: Please provide a link only. Please provide the RAW content of the file if you use an image from a GitHub repo. We kindly request that the image be provided in a square format, ensuring equal width and height for a polished visual appearance.
    validations:
      required: true

  - type: textarea
    id: project-leads
    attributes:
      label: Project lead
      description: Your name and GitHub login
      placeholder: One per line
    validations:
      required: true

  - type: textarea
    id: skills
    attributes:
      label: Skills
      description: Please provide skills you expect contributors to have, so others can have better ideas if they can join. You can include non-technical skills, or simply write None, check [the guide](https://github.com/ohbm/hackathon2025/blob/main/PROJECTS_HANDBOOK.md#onboarding-skills) for more suggestions.
    validations:
      required: true

  - type: textarea
    id: tutorials
    attributes:
      label: Recommended tutorials for new contributors
      description: "Please provide a list of tutorials that might be helpful for new contributors. Make sure to include the link to the tutorials here. Several great examples of such tutorials can be found at the following places: [traintrack online selection](https://ohbm.github.io/hackathon2023/traintrack/), [brainhack school modules](https://school-brainhack.github.io/modules/), [Neurohackademy lectures](https://neurohackademy.org/course_type/lectures/), and [brainhack's youtube channel](https://www.youtube.com/c/brainhackorg/playlists)"
      placeholder: One per line
    validations:
      required: false

  - type: textarea
    id: issues
    attributes:
      label: Good first issues
      description: If you welcome new contributors, please provide a list of good-first-issues (not required, but highly recommended), check [the guide](https://github.com/ohbm/hackathon2025/blob/main/PROJECTS_HANDBOOK.md#good-first-issues) for suggestions
    validations:
      required: false

  - type: checkboxes
    id: coc
    attributes:
      label: "Please read and follow the OHBM Code of Conduct"
      description: Read here [the OHBM Code of Conduct](https://ohbm.github.io/hackathon2025/code-of-conduct/)
      options:
        - label: I agree to follow the OHBM Code of Conduct during the hackathon
          required: true
